# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://nationalfreedommovement.uk'
baseurl: ''
title: 'National Freedom Movement'
description: 'Securing National Freedom for the British people.'
permalink: pretty
logo: "https://scontent-lhr3-1.xx.fbcdn.net/v/t1.0-9/56718534_317487205636375_6262482391139352576_n.png?_nc_cat=110&_nc_ht=scontent-lhr3-1.xx&oh=c53b6fdccb66eff2a23a03dbc0dd4312&oe=5D091240"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: News
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
