# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://nationalfreedommovement.uk'
baseurl: ''
title: 'National Freedom Movement'
description: 'Securing National Freedom for the British people.'
permalink: pretty
logo: "https://scontent-lhr3-1.xx.fbcdn.net/v/t1.0-9/56448963_317450018973427_6965440328425799680_n.jpg?_nc_cat=111&_nc_ht=scontent-lhr3-1.xx&oh=9c7f9f2eb8e166651bfb67f1ef5c1b14&oe=5D4210AC"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
